# Generated by Django 2.2 on 2021-04-17 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(help_text='Must be 5 characters. Example: SN5ab', max_length=5, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in Dollars', max_digits=6)),
            ],
        ),
    ]
