# Generated by Django 2.2 on 2021-04-17 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciberc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('xls', 'xlsx'))])),
                ('date', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='id',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='serial_number',
            field=models.CharField(help_text='Must be 5 characters. Example: SN5ab', max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
