# Generated by Django 2.2 on 2021-04-17 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciberc', '0002_auto_20210417_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileload',
            name='name',
        ),
    ]
