# Generated by Django 2.2 on 2021-04-17 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciberc', '0003_remove_fileload_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileload',
            name='file',
            field=models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('xls', 'xlsx'))]),
        ),
    ]
