# Generated by Django 2.2 on 2021-04-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciberc', '0004_auto_20210417_0824'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileLoad',
        ),
    ]
