# Generated by Django 2.2 on 2021-04-18 02:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciberc', '0006_fileload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileload',
            name='file',
            field=models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('xlsb',))]),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in Dollars', max_digits=8),
        ),
    ]
