# Generated by Django 2.2 on 2021-04-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciberc', '0007_auto_20210417_2110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileLoad',
        ),
    ]
